export interface AppConfig {
  bindHost: string;
  port: number;
  publicOrigin: URL;
  mcpServerUrl: URL;
  allowedHosts: string[];
  oauth: {
    clientId: string;
    redirectUri: string;
    clientsFile: string;
    ownerCodeHash: string;
    signingSecret: string;
  };
  agently: {
    binary: string;
    configDir: string;
    workspace: string;
    accessToken?: string;
    timeoutMs: number;
  };
}

function required(env: NodeJS.ProcessEnv, name: string): string {
  const value = env[name]?.trim();
  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`);
  }
  return value;
}

function parseInteger(value: string | undefined, fallback: number, min: number, max: number): number {
  if (!value) {
    return fallback;
  }
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed < min || parsed > max) {
    throw new Error(`Expected an integer between ${min} and ${max}`);
  }
  return parsed;
}

export function loadConfig(env: NodeJS.ProcessEnv = process.env): AppConfig {
  const publicOrigin = new URL(required(env, "MCP_PUBLIC_ORIGIN"));
  if (publicOrigin.pathname !== "/" || publicOrigin.search || publicOrigin.hash) {
    throw new Error("MCP_PUBLIC_ORIGIN must be an origin without path, query, or fragment");
  }
  if (env.NODE_ENV === "production" && publicOrigin.protocol !== "https:") {
    throw new Error("MCP_PUBLIC_ORIGIN must use HTTPS in production");
  }

  const redirectUri = required(env, "OAUTH_REDIRECT_URI");
  const redirect = new URL(redirectUri);
  if (redirect.protocol !== "https:") {
    throw new Error("OAUTH_REDIRECT_URI must use HTTPS");
  }
  if (redirect.origin !== "https://chatgpt.com" || !redirect.pathname.startsWith("/connector/oauth/")) {
    throw new Error("OAUTH_REDIRECT_URI must be the exact ChatGPT connector callback URL");
  }

  const signingSecret = required(env, "OAUTH_SIGNING_SECRET");
  if (signingSecret.length < 32) {
    throw new Error("OAUTH_SIGNING_SECRET must be at least 32 characters");
  }

  const ownerCodeHash = required(env, "OAUTH_OWNER_CODE_HASH");
  if (!ownerCodeHash.startsWith("scrypt$")) {
    throw new Error("OAUTH_OWNER_CODE_HASH must be generated by the bundled helper");
  }

  const accessToken = env.AGENTLY_ACCESS_TOKEN?.trim() || undefined;
  if (accessToken && accessToken === signingSecret) {
    throw new Error("Agent Mail and MCP OAuth secrets must be independent");
  }

  return {
    bindHost: env.HOST?.trim() || "0.0.0.0",
    port: parseInteger(env.PORT, 3000, 1, 65_535),
    publicOrigin,
    mcpServerUrl: new URL("/mcp", publicOrigin),
    allowedHosts: [publicOrigin.hostname],
    oauth: {
      clientId: required(env, "OAUTH_CLIENT_ID"),
      redirectUri,
      clientsFile: env.OAUTH_CLIENTS_FILE?.trim() || "/data/agently-cli/oauth-clients.json",
      ownerCodeHash,
      signingSecret,
    },
    agently: {
      binary: env.AGENTLY_BIN?.trim() || "agently-cli",
      configDir: env.AGENTLY_CLI_CONFIG_DIR?.trim() || "/data/agently-cli",
      workspace: env.AGENTLY_WORKSPACE?.trim() || "default",
      accessToken,
      timeoutMs: parseInteger(env.AGENTLY_TIMEOUT_MS, 20_000, 1_000, 60_000),
    },
  };
}

